# Spring Cleaning!

Harold's stock data is a mess! Help him clean up his data before the auditors arrive!

In [1]:
# Import Libraries
import pandas as pd
from pathlib import Path

### Load CSV data into Pandas using `read_csv`

In [14]:
csv_path = Path("../../Resources/stock_data.csv")
df = pd.read_csv(csv_path)
df.sample(5)

,symbol,name,sector,price,price_per_earnings,dividend_yield,earnings_per_share,52_week_low,52_week_high,market_cap,ebitda,price_per_sales,price_per_book,sec_filings
184,XOM,Exxon Mobil Corp.,Energy,76.07,21.37,4.003120,1.88,89.30,76.050,3.261487e+11,3.905200e+10,1.770194,1.85,http://www.sec.gov/cgi-bin/browse-edgar?action...
98,CTL,CenturyLink Inc,Telecommunication Services,16.2,8.35,12.661196,1.16,27.61,13.161,1.823720e+10,NaN,1.479598,1.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
308,MCHP,Microchip Technology,Information Technology,79.9,21.77,1.751297,0.66,99.17,69.760,1.939310e+10,9.974920e+08,7.447518,5.90,http://www.sec.gov/cgi-bin/browse-edgar?action...
26,GOOGL,Alphabet Inc Class A,Information Technology,1007.71,31.48,0.000000,22.27,1198.00,824.300,7.338240e+11,3.421700e+10,6.801692,4.70,http://www.sec.gov/cgi-bin/browse-edgar?action...
414,SLG,SL Green Realty,Real Estate,90.61,14.07,3.499892,0.88,115.34,91.200,8.617714e+09,7.958890e+08,6.582008,1.32,http://www.sec.gov/cgi-bin/browse-edgar?action...

### Identify the number of rows and columns (shape) in the DataFrame.

In [4]:
df.shape

(504, 14)

### Generate a sample of the data to visually ensure data has been loaded in correctly.

In [6]:
df.sample(10)

,symbol,name,sector,price,price_per_earnings,dividend_yield,earnings_per_share,52_week_low,52_week_high,market_cap,ebitda,price_per_sales,price_per_book,sec_filings
304,MET,MetLife Inc.,Financials,44.28,8.52,3.458712,0.63,56.58,44.5800,4.867936e+10,0.000000e+00,1.049686,0.85,http://www.sec.gov/cgi-bin/browse-edgar?action...
131,CCI,Crown Castle International Corp.,Real Estate,103.81,21.45,3.862069,1.02,114.97,86.9300,4.418302e+10,2.292600e+09,10.125291,3.54,http://www.sec.gov/cgi-bin/browse-edgar?action...
134,CMI,Cummins Inc.,Industrials,165.73,16.83,2.500868,8.23,194.18,143.8301,2.866923e+10,2.924000e+09,1.940617,3.89,http://www.sec.gov/cgi-bin/browse-edgar?action...
494,WYNN,Wynn Resorts Ltd,Consumer Discretionary,169.28,31.70,1.127904,7.27,203.63,92.6700,1.822540e+10,1.501301e+09,2.478658,51.69,http://www.sec.gov/cgi-bin/browse-edgar?action...
290,M,Macy's Inc.,Consumer Discretionary,24,7.67,6.098546,1.98,33.73,17.4050,7.541063e+09,2.446000e+09,0.455032,1.69,http://www.sec.gov/cgi-bin/browse-edgar?action...
103,CHK,Chesapeake Energy,Energy,2.82,4.70,0.000000,-6.44,6.59,2.8000,2.626102e+09,1.470000e+09,0.407652,1.84,http://www.sec.gov/cgi-bin/browse-edgar?action...
52,APTV,Aptiv Plc,Consumer Discretionary,89.27,69.74,0.939268,5.05,96.91,82.9700,2.490653e+10,2.370000e+09,1.502580,7.56,http://www.sec.gov/cgi-bin/browse-edgar?action...
400,RCL,Royal Caribbean Cruises Ltd,Consumer Discretionary,122.45,16.26,1.867414,7.53,135.65,93.4000,2.741815e+10,2.876309e+09,3.102661,2.56,http://www.sec.gov/cgi-bin/browse-edgar?action...
388,O,Realty Income Corporation,Real Estate,47.56,15.54,5.372036,1.12,63.60,48.8900,1.378494e+10,1.075568e+09,15.588069,1.92,http://www.sec.gov/cgi-bin/browse-edgar?action...
234,HRL,Hormel Foods Corp.,Consumer Staples,32.21,20.39,2.290776,1.57,38.00,29.7500,1.733861e+10,1.422305e+09,2.517479,3.49,http://www.sec.gov/cgi-bin/browse-edgar?action...

### Identify the number of records in the DataFrame, and compare it with the number of rows in the original file.

In [7]:
df.count()

symbol                504
name                  502
sector                501
price                 500
price_per_earnings    497
dividend_yield        499
earnings_per_share    498
52_week_low           500
52_week_high          500
market_cap            500
ebitda                492
price_per_sales       500
price_per_book        492
sec_filings           500
dtype: int64

### Identify nulls records

In [9]:
df.isnull().sum()

symbol                 0
name                   2
sector                 3
price                  4
price_per_earnings     7
dividend_yield         5
earnings_per_share     6
52_week_low            4
52_week_high           4
market_cap             4
ebitda                12
price_per_sales        4
price_per_book        12
sec_filings            4
dtype: int64

### Drop Null Records

In [10]:
df = df.dropna().copy()

### Validate nulls have been dropped

In [12]:
df = df.dropna().copy()

### Default null `ebitda` values to 0. Then, validate no records are null for ebitda.

In [17]:
df['ebitda'].fillna(0,inplace=True)

### Drop Duplicates

In [18]:
new_df = df.drop_duplicates().copy()

In [22]:
new_df.head()

,symbol,name,sector,price,price_per_earnings,dividend_yield,earnings_per_share,52_week_low,52_week_high,market_cap,ebitda,price_per_sales,price_per_book,sec_filings
0,MMM,3M Company,Industrials,$222.89,24.31,2.332862,$7.92,259.770,175.49,1.387211e+11,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.600,42.28,1.021210e+11,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.860,60.05,1.813863e+11,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ATVI,Activision Blizzard,Information Technology,65.83,NaN,0.431903,1.28,74.945,38.93,5.251867e+10,2.704000e+09,10.595120,5.16,http://www.sec.gov/cgi-bin/browse-edgar?action...